PHONETIC_ALPHABET_DICT = {
    "A": "Alpha",
    "B": "Bravo",
    "C": "Charlie",
    "D": "Delta",
    "E": "Echo",
    "F": "Foxtrot",
    "G": "Golf",
    "H": "Hotel",
    "I": "India",
    "J": "Juliett",
    "K": "Kilo",
    "L": "Lima",
    "M": "Mike",
    "N": "November",
    "O": "Oscar",
    "P": "Papa",
    "Q": "Quebec",
    "R": "Romeo",
    "S": "Sierra",
    "T": "Tango",
    "U": "Uniform",
    "V": "Victor",
    "W": "Whiskey",
    "X": "Xray",
    "Y": "Yankee",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
    "0": "Zero"
}

KEYPAD_MAPPING = {
    "A": "2",
    "B": "2",
    "C": "2",
    "D": "3",
    "E": "3",
    "F": "3",
    "G": "4",
    "H": "4",
    "I": "4",
    "J": "5",
    "K": "5",
    "L": "5",
    "M": "6",
    "N": "6",
    "O": "6",
    "P": "7",
    "Q": "7",
    "R": "7",
    "S": "7",
    "T": "8",
    "U": "8",
    "V": "8",
    "W": "9",
    "X": "9",
    "Y": "9",
    "Z": "9"
}

# This mapping is the number of the letter on the specific number for XX
# insurance
KEYPAD_MAPPING_LOW_LEVEL = {
    "A": "1",
    "B": "2",
    "C": "3",
    "D": "1",
    "E": "2",
    "F": "3",
    "G": "1",
    "H": "2",
    "I": "3",
    "J": "1",
    "K": "2",
    "L": "3",
    "M": "1",
    "N": "2",
    "O": "3",
    "P": "1",
    "Q": "2",
    "R": "3",
    "S": "4",
    "T": "1",
    "U": "2",
    "V": "3",
    "W": "1",
    "X": "2",
    "Y": "*",  # I think these last two are actually *
    "Z": "*"
}

MONTH_STR_TO_NUM = {
    "january": "01",
    "february": "02",
    "march": "03",
    "april": "04",
    "may": "05",
    "june": "06",
    "july": "07",
    "august": "08",
    "september": "09",
    "october": "10",
    "november": "11",
    "december": "12"
}
